ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "invoiceType"  TEXT NOT NULL DEFAULT 'bireysel';
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "companyTitle" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "taxOffice"    TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "city"         TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "district"     TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "postalCode"   TEXT;
