ALTER TABLE "SyncLog" ADD COLUMN "xmlSourceId" TEXT;
ALTER TABLE "SyncLog" ADD COLUMN "created" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN "updated" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN "skipped" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX "SyncLog_xmlSourceId_idx" ON "SyncLog"("xmlSourceId");

ALTER TABLE "SyncLog" ADD CONSTRAINT "SyncLog_xmlSourceId_fkey"
  FOREIGN KEY ("xmlSourceId") REFERENCES "XmlSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
