-- Add maxProducts and maxXmlSources to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxProducts" INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxXmlSources" INTEGER NOT NULL DEFAULT 3;
